### ISSUE TITLE
Compiling error with 'weaver'

### ISSUE THREAD

**Issue by RebelLion420** [PitchBlackRecoveryProject/android_bootable_recovery#31]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: perry
**TWRP version**: 3.2.3

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Sync source 'twrp-7.1' branch and device trees
source build/envsetup.sh
lunch omni_device-eng
mka -j$(nproc --all) recoveryimage

#### WHAT IS THE EXPECTED RESULT?
Complete build

#### WHAT HAPPENS INSTEAD?
Build fails with error "android.hardware.weaver@1.0.so missing and no known rule to make it"

Build log: https://del.dog/rirupifeci 

#### ADDITIONAL INFORMATION
These 2 commits have been identified as the additions of the calls for 'weaver', however reverting them does not solve the issue

https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/commit/55b0884de7c059011b5e197b6e2ac0eef14dae08

https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/commit/33d2a72e55025dd75e9072ba7e3e3423298141fe

Device tree: https://github.com/RebelLion420/android_device_motorola_perry

Common tree: https://github.com/RebelLion420/android_device_motorola_msm8937-common

Kernel source: https://github.com/RebelLion420/android_kernel_motorola_msm8937

**Comment by RebelLion420** [comment]
Found it! It's necessary to use the PBRP branch even when building for Nougat (twrp-7.1). I also was forced to use optipng to crunch the bootable/recovery/gui folder small enough to fit in the kernel partition. Before optipng recovery.img was >19mb, afterwards it shrank to 17.05mb. Just small enough to fit lol. So maybe this should be included in the directions or done on PBRP's side beforehand

**Comment by AndroiableDroid** [comment]
https://github.com/PitchBlackRecoveryProject/manifest_pb/commit/c23b0c7f90b78fa30aa608a30817d35bf3199455
This error should be fixed now

**Comment by RebelLion420** [comment]
> [PitchBlackRecoveryProject/manifest_pb@c23b0c7](https://github.com/PitchBlackRecoveryProject/manifest_pb/commit/c23b0c7f90b78fa30aa608a30817d35bf3199455)
> This error should be fixed now

I think this actually caused another error relating to sepolicy now. Cannot find anything other than one other person's pastebin on the same error with a google search.

`bootable/recovery/sepolicy/pbrp.te:16:ERROR 'unknown type sysfs_dm' at token ';' on line 22178:`

`allow recovery sysfs:file getattr;`

`allow recovery sysfs_dm:dir { open read search };`

`checkpolicy:  error(s) encountered while parsing configuration`

**Comment by AndroiableDroid** [comment]
Repo sync and retry compiling

**Comment by manjotsidhu** [comment]
Closing issue because of no response.
