### ISSUE TITLE
Add flag to Keep Encryption

### ISSUE THREAD

**Issue by raza231198** [PitchBlackRecoveryProject/android_bootable_recovery#47]
@AndroiableDroid  Please add flags to Disable Patching for force encryption.

Some devices have issues with decryption, and user don't wanna to decrypt your device.

When user is formatting device and flashing rom it disable force encryption if we don't select to Disable force encryption or not.

So either add flags to hide that option or disabled bu default and not patching after formatting too

**Comment by ahmedmoselhi** [comment]
@AndroiableDroid please sir, I have this problem on rmx1851 aka realme 3 pro

**Comment by AndroiableDroid** [comment]
What problem you facing guys?

**Comment by ahmedmoselhi** [comment]
> What problem you facing guys?

The option "advanced disable force encryption" while flashing a zip is enabled by default. I want to disable it

**Comment by ahmedmoselhi** [comment]
@AndroiableDroid also check this https://github.com/PitchBlackRecoveryProject-Devices/android_bootable_recovery/commit/3e08ef605c4b06da716b577b6873380b6aa34563#diff-9a54647879e21edd32ca9f0280d75d73L1863

**Comment by AndroiableDroid** [comment]
> @AndroiableDroid also check this https://github.com/PitchBlackRecoveryProject-Devices/android_bootable_recovery/commit/3e08ef605c4b06da716b577b6873380b6aa34563#diff-9a54647879e21edd32ca9f0280d75d73L1863

That's not a good way to doing it

**Comment by AndroiableDroid** [comment]
Let me think. Will trigger a build for your device so that you can test it.

**Comment by ahmedmoselhi** [comment]
> Let me think. Will trigger a build for your device so that you can test it.
@androiabledroid works fine bro! force encryption patch is disabled by default
