### ISSUE TITLE
ld.lld: error

### ISSUE THREAD

**Issue by smlinux** [PitchBlackRecoveryProject/android_bootable_recovery#83]
ld.lld: error: duplicate symbol: getdtablesize
>>> defined at general.c:1179 (external/bash/general.c:1179)
>>>            /home/name/Android/source/android/pbrp-10.0/out/target/product/angelican/obj/EXECUTABLES/bash_intermediates/general.o:(getdtablesize)
>>> defined at oslib.c:147 (external/bash/lib/sh/oslib.c:147)
>>>            oslib.o:(.text.getdtablesize+0x0) in archive /home/name/Android/source/android/pbrp-10.0/out/target/product/angelican/obj/STATIC_LIBRARIES/libsh_intermediates/libsh.a
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
[error.log](https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/files/6565906/error.log)

09:54:19 ninja failed with: exit status 1

**Comment by DelightReza** [comment]
> ld.lld: error: duplicate symbol: getdtablesize
> 
> > > > defined at general.c:1179 (external/bash/general.c:1179)
> > > > /home/name/Android/source/android/pbrp-10.0/out/target/product/angelican/obj/EXECUTABLES/bash_intermediates/general.o:(getdtablesize)
> > > > defined at oslib.c:147 (external/bash/lib/sh/oslib.c:147)
> > > > oslib.o:(.text.getdtablesize+0x0) in archive /home/name/Android/source/android/pbrp-10.0/out/target/product/angelican/obj/STATIC_LIBRARIES/libsh_intermediates/libsh.a
> > > > clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
> > > > [error.log](https://github.com/PitchBlackRecoveryProject/android_bootable_recovery/files/6565906/error.log)
> 
> 09:54:19 ninja failed with: exit status 1

Tree?

**Comment by smlinux** [comment]
Today, after synchronizing the repositories, everything is build fine.
