### ISSUE TITLE
[Feature Request] add parameters for other partitions in openrecoveryscript

### ISSUE THREAD

**Issue by suppqt** [PitchBlackRecoveryProject/android_bootable_recovery#97]
### Is your feature request related to a problem? If yes, please describe.

Backing up device via tasker and openrecoveryscript file in /cache
using backup SDBOM commandline

![image](https://user-images.githubusercontent.com/3234897/221893452-a965c05b-abd2-46fb-9eba-781fab8b7a23.png)

### Describe the solution/feature you'd like

Adding more partitions to get a fully possible backup via commandline on my z3s

**metadata
Cache
efs
sec_efs
modem
dtbo
CP Debug
Optics Image
Param
Prism Image
Super**

compiling openrecoveryscript.java with more bacup parameters

![image](https://user-images.githubusercontent.com/3234897/221893950-5e01425e-6c93-4a9f-8118-8bddf4f67d81.png)

### Describe alternatives you've considered

none found

**Comment by Nico170420** [comment]
First, I think this is the wrong section to request that, bc this is device related, secondly I won't add it to backup bc many of them shouldn't be touched. Regards.
